export  const firstColumnSeat = [
    {is_booked:false,is_available:true,seat_no:"A1" },
    {is_booked:false,is_available:true,seat_no:"A2" },
    {is_booked:false,is_available:true,seat_no:"A3" },
    {is_booked:true,is_available:false,seat_no:"A4" },
    {is_booked:false,is_available:true,seat_no:"A5" },
    {is_booked:true,is_available:false,seat_no:"A6" },
    {is_booked:false,is_available:true,seat_no:"A7" },
    {is_booked:false,is_available:true,seat_no:"A8" },
    {is_booked:true,is_available:false,seat_no:"A9" },
    {is_booked:false,is_available:true,seat_no:"A10" },
    {is_booked:true,is_available:false,seat_no:"A11" },
    {is_booked:false,is_available:true,seat_no:"A12" },
    {is_booked:false,is_available:true,seat_no:"A13" },
    {is_booked:true,is_available:false,seat_no:"A14" },
    {is_booked:false,is_available:true,seat_no:"A15" },
    {is_booked:false,is_available:true,seat_no:"B1" },
    {is_booked:true,is_available:false,seat_no:"B2" },
    {is_booked:false,is_available:true,seat_no:"B3" },
    {is_booked:false,is_available:true,seat_no:"B4" },
    {is_booked:false,is_available:true,seat_no:"B5" },
    {is_booked:false,is_available:true,seat_no:"B6" },
    {is_booked:true,is_available:false,seat_no:"B7" },
    {is_booked:false,is_available:true,seat_no:"B8" },
    {is_booked:false,is_available:true,seat_no:"B9" },
    {is_booked:true,is_available:false,seat_no:"B10" },
    {is_booked:false,is_available:true,seat_no:"B11" },
    {is_booked:false,is_available:true,seat_no:"B12" },
    {is_booked:true,is_available:false,seat_no:"B13" },
    {is_booked:false,is_available:true,seat_no:"B14" },
    {is_booked:false,is_available:true,seat_no:"B15" },

]
export const secondColumnSeat = [
    {is_booked:false,is_available:true,seat_no:"C1" },
    {is_booked:false,is_available:true,seat_no:"C2" },
    {is_booked:false,is_available:true,seat_no:"C3" },
    {is_booked:false,is_available:true,seat_no:"C4" },
    {is_booked:false,is_available:true,seat_no:"C5" },
    {is_booked:false,is_available:true,seat_no:"C6" },
    {is_booked:false,is_available:true,seat_no:"C7" },
    {is_booked:false,is_available:true,seat_no:"C8" },
    {is_booked:false,is_available:true,seat_no:"C9" },
    {is_booked:false,is_available:true,seat_no:"C10" },
    {is_booked:false,is_available:true,seat_no:"C11" },
    {is_booked:false,is_available:true,seat_no:"C12" },
    {is_booked:false,is_available:true,seat_no:"C13" },
    {is_booked:false,is_available:true,seat_no:"C14" },
    {is_booked:false,is_available:true,seat_no:"C15" },
    {is_booked:false,is_available:true,seat_no:"D1" },
    {is_booked:false,is_available:true,seat_no:"D2" },
    {is_booked:false,is_available:true,seat_no:"D3" },
    {is_booked:false,is_available:true,seat_no:"D4" },
    {is_booked:false,is_available:true,seat_no:"D5" },
    {is_booked:false,is_available:true,seat_no:"D6" },
    {is_booked:false,is_available:true,seat_no:"D7" },
    {is_booked:true,is_available:false,seat_no:"D8" },
    {is_booked:false,is_available:true,seat_no:"D9" },
    {is_booked:false,is_available:true,seat_no:"D10" },
    {is_booked:false,is_available:true,seat_no:"D11" },
    {is_booked:false,is_available:true,seat_no:"D12" },
    {is_booked:true,is_available:false,seat_no:"D13" },
    {is_booked:false,is_available:true,seat_no:"D14" },
    {is_booked:false,is_available:true,seat_no:"D15" },

]

export const thirdColumnSeat = [
    {is_booked:true,is_available:false,seat_no:"E1" },
    {is_booked:true,is_available:false,seat_no:"E2" },
    {is_booked:false,is_available:true,seat_no:"E3" },
    {is_booked:false,is_available:true,seat_no:"E4" },
    {is_booked:false,is_available:true,seat_no:"E5" },
    {is_booked:false,is_available:true,seat_no:"E6" },
    {is_booked:true,is_available:false,seat_no:"E7" },
    {is_booked:false,is_available:true,seat_no:"E8" },
    {is_booked:true,is_available:false,seat_no:"E9" },
    {is_booked:false,is_available:true,seat_no:"E10" },
    {is_booked:false,is_available:true,seat_no:"E11" },
    {is_booked:true,is_available:false,seat_no:"E12" },
    {is_booked:false,is_available:true,seat_no:"E13" },
    {is_booked:false,is_available:true,seat_no:"E14" },
    {is_booked:false,is_available:true,seat_no:"E15" },
    {is_booked:false,is_available:true,seat_no:"F1" },
    {is_booked:false,is_available:true,seat_no:"F2" },
    {is_booked:true,is_available:false,seat_no:"F3" },
    {is_booked:false,is_available:true,seat_no:"F4" },
    {is_booked:true,is_available:false,seat_no:"F5" },
    {is_booked:false,is_available:true,seat_no:"F6" },
    {is_booked:true,is_available:false,seat_no:"F7" },
    {is_booked:false,is_available:true,seat_no:"F8" },
    {is_booked:true,is_available:false,seat_no:"F9" },
    {is_booked:false,is_available:true,seat_no:"F10" },
    {is_booked:false,is_available:true,seat_no:"F11" },
    {is_booked:true,is_available:false,seat_no:"F12" },
    {is_booked:false,is_available:true,seat_no:"F13" },
    {is_booked:false,is_available:true,seat_no:"F14" },
    {is_booked:false,is_available:true,seat_no:"F15" },

]